### ISSUE TITLE
Train model with different image size

### ISSUE THREAD

**Issue by nhat120904** [buggyyang/CDC_compression#23]
Thank you for your work on this repository. It has been incredibly helpful for my project!
I am currently working with images that are of varying sizes, and I would like to train the model using these different image dimensions (ex: VGA size). However, I noticed that the training process seems to expect a fixed input size.
Could you provide some guidance or suggestions on how to modify the training pipeline to support varying image sizes? Should the images be resized or padded, or is there an alternative approach that would allow the model to handle different sizes natively?

**Comment by buggyyang** [comment]
for training, you can use fixed size, because the model is fully convolutional and can be applied to different resolutions for inference so we simply use 256 as training resolution. The improvement from using higher resolution for training is marginal and the training time can be unacceptable. For inference, you need to pad the images to the supported size. Note that these are typical methods people used to train/inference a neural compression model
